import Foundation

/// Swift contract for the bundled **official Demucs** (`htdemucs_ft`) models,
/// decoded from `htdemucs_manifest.json` (generated by `tools/convert_htdemucs.py`).
/// Every segment / STFT / source parameter the backend uses comes from here — no
/// constants carried from memory (mission guardrail). `htdemucs_ft` is a bag of
/// four fine-tuned nets, one per stem; `models` lists each with the source index
/// it owns (identity mixing weights → source *i* comes from model *i*).
///
/// Property names mirror the JSON's snake_case keys via `.convertFromSnakeCase`.
struct DemucsManifest: Decodable, Sendable {
    let sources: [String]
    let sampleRate: Double         // sample_rate
    let channels: Int
    let segmentSamples: Int        // segment_samples
    let nfft: Int
    let hop: Int
    let bins: Int
    let frames: Int
    let inputs: [String]
    let outputs: [String]
    let models: [ModelEntry]

    struct ModelEntry: Decodable, Sendable {
        /// Bundle resource base name, e.g. `htdemucs_ft_vocals` (compiled `.mlmodelc`).
        let resource: String
        let source: String
        let sourceIndex: Int       // source_index
    }

    static func bundled(resourceName: String = "htdemucs_manifest") -> DemucsManifest? {
        guard let url = Bundle.main.url(forResource: resourceName, withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            return nil
        }
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try? decoder.decode(DemucsManifest.self, from: data)
    }
}
